services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dipec12345@
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 djangochatapi.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DEBUG=1
      - REDIS_URL=redis://redis:6379
      - DJANGO_SETTINGS_MODULE=djangochatapi.settings

volumes:
  postgres_data:
