# Generated by Django 5.2.3 on 2025-06-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='user', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
