# Generated by Django 5.2.3 on 2025-06-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
