name: CI with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  docker-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: docker compose version

      - name: Build and start services
        run: docker compose up -d --build

      - name: Wait for DB to be ready
        run: |
          until docker compose exec -T db pg_isready -U postgres; do
            echo "Waiting for db..."; sleep 2;
          done

      - name: Run migrations
        run: docker compose exec -T web python manage.py migrate

      - name: Run tests
        run: docker compose exec -T web python manage.py test
      
      - name: Run all Pytest tests
        run: docker compose exec -T web pytest chat/tests/

      - name: Shut down
        run: docker compose down
